# Generated by Django 4.2.28 on 2026-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('none', 'Nenhum'), ('new', 'Novo'), ('not_visited', 'Não visitado'), ('visited', 'Visitado'), ('interested', 'Interessado'), ('not_interested', 'Não interessado'), ('revisit', 'Visitar novamente'), ('lead', 'Lead'), ('contract', 'Contrato fechado'), ('client', 'Cliente'), ('past_client', 'Já comprou')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('base', 'Base'), ('client', 'Cliente')], default='base', max_length=10),
        ),
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
