# Generated by Django 4.2.28 on 2026-02-11 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_email_house_phone_house_status_house_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='radius',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='house',
            name='registered_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
