# Generated by Django 4.2.28 on 2026-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_age_house_radius_house_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='business_type',
            field=models.CharField(choices=[('barbearia', 'Barbearia'), ('salao', 'Salão de Beleza'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('estetica', 'Estética'), ('outro', 'Outro')], default='barbearia', max_length=30),
        ),
        migrations.AddField(
            model_name='house',
            name='custom_business',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
