# Generated by Django 4.2.28 on 2026-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_business_type_house_custom_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='business_type',
            field=models.CharField(choices=[('barbearia', 'Barbearia'), ('salao', 'Salão de Beleza'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('estetica', 'Estética'), ('outro', 'Outro')], default='none', max_length=30),
        ),
    ]
